### ISSUE TITLE
The RoborazziRule.Options constructor is treated as @ExperimentalRoborazziApi

### ISSUE THREAD

**Issue by colinrtwhite** [takahirom/roborazzi#565] opened 2024-11-21 19:51 UTC
The `RoborazziRule.Options` is treated as being marked with `@ExperimentalRoborazziApi` in the latest 1.33.0 version. This is because it includes an argument with the experimental type `AccessibilityCheckStrategy`. Having at least one experimental property means the whole constructor is treated as experimental even if the experimental argument isn't set.

**Comment by colinrtwhite** [comment] 2024-11-21 22:57
To fix this I think you'll need to add a secondary constructor that doesn't include the experimental argument similar to what I've done with the multiple overloads [here](https://github.com/coil-kt/coil/blob/main/coil-network-okhttp/src/commonMain/kotlin/coil3/network/okhttp/OkHttpNetworkFetcher.kt).

**Comment by takahirom** [comment] 2024-11-22 02:44
Thanks for reporting and suggesting a solution.  
I'm concerned that we might need constructors like \( N^N \) or a similar number. However, I think we can provide one secondary constructor that uses only stable parameters, and we’ll have a main constructor that includes both stable and experimental parameters. In this way, we might only need to maintain two constructors. (Though it does not ensure binary compatibility.)


```kotlin
data class Options(
  val captureType: CaptureType = CaptureType.None,
  /**
   * output directory path
   */
  val outputDirectoryPath: String = provideRoborazziContext().outputDirectory,

  val outputFileProvider: FileProvider = provideRoborazziContext().fileProvider
    ?: defaultFileProvider,
  val roborazziOptions: RoborazziOptions = provideRoborazziContext().options,
  val roborazziAccessibilityOptions: RoborazziAccessibilityOptions = provideRoborazziContext().roborazziAccessibilityOptions,
  val accessibilityCheckStrategy: AccessibilityCheckStrategy = AccessibilityCheckStrategy.None,
) {
  // Stable parameters
  constructor(
    captureType: CaptureType = CaptureType.None,
    /**
     * output directory path
     */
    outputDirectoryPath: String = provideRoborazziContext().outputDirectory,

    outputFileProvider: FileProvider = provideRoborazziContext().fileProvider
      ?: defaultFileProvider,
    roborazziOptions: RoborazziOptions = provideRoborazziContext().options,
  ): this(
    captureType = captureType,
    outputDirectoryPath = outputDirectoryPath,
    outputFileProvider = outputFileProvider,
    roborazziOptions = roborazziOptions,
    roborazziAccessibilityOptions = provideRoborazziContext().roborazziAccessibilityOptions,
    accessibilityCheckStrategy = AccessibilityCheckStrategy.None
  )
}
```

**Comment by takahirom** [comment] 2024-11-22 02:50
We have a problem where we can't see the warning from `@RequiresOptIn` in the sample-android module, which makes fixing the issue difficult. 👀

**Comment by takahirom** [comment] 2024-11-22 03:38
I found the cause of the problem. 👀 
https://github.com/takahirom/roborazzi/blob/main/build.gradle#L51-L52

**Comment by takahirom** [comment] 2024-11-23 02:08
@ZacSweers
I made a change to add stable constructors. Could you check it out a little?
https://github.com/takahirom/roborazzi/pull/566/files#diff-9012f191f9216650ef0280cd21cf411514ed71502bdf5e2d122ffcb60be7727eR82

**Comment by colinrtwhite** [comment] 2024-11-23 22:53
@takahirom The proposed changes look good to me!

**Comment by takahirom** [comment] 2024-11-24 02:24
Thank you for reporting this issue and reviewing the code. I've released the changes—could you check if it works?

**Comment by colinrtwhite** [comment] 2024-11-24 21:01
[It works](https://github.com/coil-kt/coil/pull/2708)! Thanks for the quick fix. Also do you mean to tag @colinrtwhite instead of @ZacSweers? 😅

**Comment by takahirom** [comment] 2024-11-25 00:49
I’m so sorry for mistakenly tagging and mentioning the wrong person in the release notes. I meant to thank you instead! Thank you so much for your contributions and support. I’ve corrected the mistake and sincerely appreciate your understanding.

**Comment by takahirom** [comment] 2024-11-25 00:52
Thank you for checking if it works. I'll go ahead and close this issue now.

**Closed by takahirom** 2024-11-25 00:52 UTC

**Comment by colinrtwhite** [comment] 2024-11-25 02:41
No problem at all! Thanks for all your hard work on this library! 🙌🏻
