### ISSUE TITLE
Allow Compose Preview Support to set Rules for automatically generated tests

### ISSUE THREAD

**Issue by TBSten** [takahirom/roborazzi#607] opened 2024-12-12 18:54 UTC
Currently, roborazzi's Compose Preview Support automatically generates a Test file for each Preview collected by [ComposablePreviewScanner](https://github.com/sergio-sastre/ComposablePreviewScanner). I believe that the Compose Preview Support currently automatically generates a Test file for each Preview collected by [ComposablePreviewScanner](). However, the automatic generation has the disadvantage that the initialization process that needs to be performed before the Test cannot be configured (e.g., see [example in this article](https://zenn.dev/karabiner_inc/articles/96603e5b89a296#roborazzi%E3%81%8Cpreview%E3%82%92%E5%85%83%E3%81%AB%E3%83%86%E3%82%B9%E3%83%88%E3%82%92%E8%87%AA%E5%8B%95%E7%94%9F%E6%88%90%E3%81%97%E3%81%A6%E3%81%84%E3%82%8B%E3%81%AE%E3%81%A7%E3%80%81%E5%B7%AE%E3%81%97%E6%9B%BF%E3%81%88%E4%B8%8D%E5%8F%AF%E8%83%BD%E3%80%82%E3%80%82) is (It may be easier to understand).

So I wondered if I could add more parameters that would allow me to set additional Rules.

```kts
roborazzi {
  generateComposePreviewRobolectricTests {
    // ...
    additionalRules = listOf(
      "com.example.myapp.SomeRule",
    )
  }
}
```

**Comment by sergio-sastre** [comment] 2024-12-12 21:44
> Currently, roborazzi's Compose Preview Support automatically generates a Test file for each Preview collected by [ComposablePreviewScanner](https://github.com/sergio-sastre/ComposablePreviewScanner). I believe that the Compose Preview Support currently automatically generates a Test file for each Preview collected by [ComposablePreviewScanner](). However, the automatic generation has the disadvantage that the initialization process that needs to be performed before the Test cannot be configured (e.g., see [example in this article](https://zenn.dev/karabiner_inc/articles/96603e5b89a296#roborazzi%E3%81%8Cpreview%E3%82%92%E5%85%83%E3%81%AB%E3%83%86%E3%82%B9%E3%83%88%E3%82%92%E8%87%AA%E5%8B%95%E7%94%9F%E6%88%90%E3%81%97%E3%81%A6%E3%81%84%E3%82%8B%E3%81%AE%E3%81%A7%E3%80%81%E5%B7%AE%E3%81%97%E6%9B%BF%E3%81%88%E4%B8%8D%E5%8F%AF%E8%83%BD%E3%80%82%E3%80%82) is (It may be easier to understand).
> 
> 
> 
> 
> 
> 
> 
> So I wondered if I could add more parameters that would allow me to set additional Rules.
> 
> 
> 
> ```kts
> 
> roborazzi {
> 
>   generateComposePreviewRobolectricTests {
> 
>     // ...
> 
>     additionalRules = listOf(
> 
>       "com.example.myapp.SomeRule",
> 
>     )
> 
>   }
> 
> }
> 
> ```
> 
> 
> 
> 

Have you checked the ComposePreviewTester?

https://github.com/DeNA/android-modern-architecture-test-handson/blob/main/docs/handson/VisualRegressionTest_Preview_ComposablePreviewScanner.md#composepreviewtester%E3%81%AE%E5%AE%9F%E8%A3%85

It has a testRuleFactory that looks like what you are looking for

**Comment by takahirom** [comment] 2024-12-13 08:23
Thanks. Yes, we have this. However, the blog in Japanese mentions that Roborazzi doesn't support `@HiltAndroidTest` for preview tests. I'm not sure if we need to support it, though. Anyway, if you encounter this kind of issue, please let us know by creating an issue. We’d like to understand your use cases. I'll close this issue for now.

**Closed by takahirom** 2024-12-13 08:23 UTC
